# Generated by Django 5.1.3 on 2025-01-22 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_font'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Font',
        ),
    ]
